import { Medic } from "./medic";

export const medics: Medic[] = [
  {
    id: 1,
    name: "Bogdan Marin",
    city: "Brasov",
    patientIds: [],
    title: "Primary Doctor",
    shortTitle: "Dr.",
    specialty: "Dermatology",
  },
  {
    id: 2,
    name: "Mirel Stanciu",
    city: "Brasov",
    patientIds: [],
    title: "Specialist Doctor",
    shortTitle: "Dr.",
    specialty: "Dermatology",
  },
  {
    id: 3,
    name: "Melania Gheorghe",
    city: "Brasov",
    patientIds: [],
    title: "Primary Doctor",
    shortTitle: "Dr.",
    specialty: "General surgery",
  },
  {
    id: 4,
    name: "Sergiu Cristian",
    city: "Bucuresti",
    patientIds: [],
    title: "Professor Primary Doctor",
    shortTitle: "Prof. Dr.",
    specialty: "Dermatology",
  },
  {
    id: 5,
    name: "Eugen Rusu",
    city: "Brasov",
    patientIds: [],
    title: "Resident Medic",
    shortTitle: "Res.",
    specialty: "Dermatology",
  },
  {
    id: 6,
    name: "David Nitu",
    city: "Brasov",
    patientIds: [],
    title: "Specialist Doctor",
    shortTitle: "Dr.",
    specialty: "Dermatology",
  },
  {
    id: 7,
    name: "Anastasia Malan",
    city: "Cluj-Napoca",
    patientIds: [],
    title: "Professor Primary Doctor",
    shortTitle: "Prof. Dr.",
    specialty: "Urology",
  },
  {
    id: 8,
    name: "Nicoleta Manolache",
    city: "Brasov",
    patientIds: [],
    title: "Specialist Doctor",
    shortTitle: "Dr.",
    specialty: "Obstetrics & Ginecology",
  },
  {
    id: 9,
    name: "Adrian Fratila",
    city: "Brasov",
    patientIds: [],
    title: "Resident Medic",
    shortTitle: "Res.",
    specialty: "Dermatology",
  },
];
